import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Streaming website',
  description:
    'Stremiang website that will display movies and TV series generated by create next app',
};

export default function Home() {
  return <div className='container mx-auto p-5'>Hello world</div>;
}
