import type { Metadata } from 'next';

import Trending from './components/trending/Trending';

export const metadata: Metadata = {
  title: 'Streaming website',
  description:
    'Streaming website that will display movies and TV series generated by create next app',
};

export default function Home() {
  return (
    <div className='container mx-auto p-5'>
      <Trending />
    </div>
  );
}
