import type { Metadata } from 'next';

import Home from '@/components/home';

export const metadata: Metadata = {
  title: 'Streaming website',
  description:
    'Streaming website that will display movies and TV series generated by create next app',
};

export default function HomePage() {
  return <Home />;
}
